trigger:
  - main
  

pool:
  vmImage: 'ubuntu-latest'

variables:
  aws.rolecredential.maxduration: '3600'

steps:
  - task: AWSCLI@1
    displayName: 'running aws-cli get-caller-identity'
    # continueOnError: true # If you need the pipeline to succeed
    inputs:
      awsCredentials: 'aws_role'
      regionName: 'aws-region-name'
      awsCommand: 'sts'
      awssubcommand: 'get-caller-identity'
