trigger:
  - azure-pipelines        # or 'none' if you want to run manually

pool:
  vmImage: 'ubuntu-latest'
   # <-- your self-hosted pool name
  # remove vmImage when using self-hosted

variables:
  aws.rolecredential.maxduration: '1700'

steps:
  - task: AWSCLI@1
    displayName: 'running aws-cli get-caller-identity'
    inputs:
      awsCredentials: 'aws_role'
      regionName: 'us-east-1'
      awsCommand: 'sts'
      awsSubCommand: 'get-caller-identity'
